#!/bin/sh
bspc config border_width        1
bspc config window_gap          0
bspc config focused_border_color "Deep Sky Blue"
bspc config urgent_border_color  "Red"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config leaf_monocle        false
bspc config focus_by_distance   true

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DVI-0 -d 6 7 8 9 0

bspc rule -a gimp state=floating
bspc rule -a qwingraph state=floating

~/.config/bspwm/panel&

